# -*- coding: utf-8 -*-
"""바이모달 트램 R3 — 대본·큐·Flow 생성표의 단일 원본.

build_r3.py 가 이 파일을 읽어 엑셀 큐시트, 큐 MD, 녹음용 TXT를 만든다.
대본을 고칠 때는 이 파일만 고치고 다시 빌드한다.
"""

DATE = "2026-10-08"
FPS = 24

SHORT_TITLE = "버스정류장 바닥만 콘크리트인 이유"
LONG_TITLE = "자석 따라 달리는 국산 트램, 도로는 버텼을까?"

# 낭독 속도(음절/초)와 컷 사이 쉼(초). 샷의 hold는 그 샷에만 더하는 의도적 정적(초). 45~75세 남성 대상이라 롱폼은 일부러 느리게 잡는다.
SHORT_RATE, SHORT_PAUSE, SHORT_TARGET = 5.4, 0.45, 58
LONG_RATE, LONG_PAUSE, LONG_TARGET = 4.9, 0.7, 600

# ---------------------------------------------------------------------------
# 근거
# status: 원문확인(R2에서 원문 대조) / 검색확인(이번 세션은 원문 접근이 차단돼 검색 색인 인용으로만 확인)
# ---------------------------------------------------------------------------
SOURCES = [
    ("F01", "특허 KR100972385B1 — 바이모달 트램 자기 유도용 자석의 도로 설치 방법", "2009-10-27 출원 / 2010-07-27 공고",
     "https://patents.google.com/patent/KR100972385B1/ko",
     "자기 유도 방식, 아스팔트 집중하중에 따른 소성·전단변형 위험, 콘크리트 포장·변형 저감 재료·정기 보수 언급",
     "특허가 있다는 사실은 현장 적용·성능·고장 원인의 증거가 아니다. 비용 추정치는 쓰지 않는다.",
     "R2 원문확인 · R3 세션 접근 차단 → 녹음 전 KIPRIS에서 문장 재대조"),
    ("F02", "철도산업정보센터 — 바이모달 트램", "개념·개발 경위",
     "https://www.kric.go.kr/jsp/industry/knp/railCommonSenceDetail.jsp?p_id1=A010031131&p_id2=159&pageNo=6&q_name=1",
     "고무차륜·굴절 차체·자기 유도·수동/자동 이중 모드 개념, 국내 개발",
     "설계 기능과 실제 노선에서 쓴 운전 모드를 구별한다.", "R2 원문확인"),
    ("F03", "인천교통공사 — 청라 GRT 바이모달 트램 투입", "2018-04-18",
     "https://www.ictr.or.kr/main/bbs/bbsMsgDetail.do?bcd=report&msg_seq=1928&pgno=108",
     "2018년 청라에 바이모달 트램 4대 투입 발표",
     "다른 지역 차량의 처분이나 2026년 현황을 증명하지 않는다.", "R2 원문확인"),
    ("F04", "인천교통공사 — 바이모달트램 관련 언론보도 해명", "2020-12-03",
     "https://www.ictr.or.kr/main/bbs/bbsMsgDetail.do?bcd=reportexplain&msg_seq=2146",
     "차체 균열·고압퓨즈·기어박스 누유와 당시 조치",
     "운영기관 설명이다. 독립 조사 결론이나 도로 파임 원인설로 넓히지 않는다.", "R2 원문확인"),
    ("F05", "FHWA — Impacts of Automated Vehicles on Highway Infrastructure (FHWA-HRT-21-015)", "2021-03, 인쇄 쪽 41–43",
     "https://www.fhwa.dot.gov/publications/research/operations/21015/21015.pdf",
     "좌우 주행 위치 분산이 줄면 포장 홈이 커질 수 있음, 위치를 분산시키는 제어 연구",
     "특정 한국 차량의 고장 원인이나 수명 단축률을 증명하지 않는다.", "R2 원문확인"),
    ("F06", "FHWA — Performance Testing for Superpave and Structural Validation, Ch.3 (FHWA-HRT-11-045)", "2012-11",
     "https://www.fhwa.dot.gov/publications/research/infrastructure/pavements/11045/003.cfm",
     "반복 바퀴 하중·온도·재료 조건과 소성변형, 하부층 기여",
     "영상의 시험 장면은 이 시험의 수치·장비를 그대로 재현한 것이 아니다.", "R2 원문확인"),
    ("F07", "Deng 외 — Modeling the rutting performance of asphalt pavements", "2023",
     "https://link.springer.com/article/10.1186/s43065-023-00082-9",
     "골재·바인더 복합재, 시간·온도 의존 반응, 잔류변형",
     "포장 전체가 액체처럼 흐른다는 표현 금지.", "R2 원문확인"),
    ("F08", "최준성 외 — 교차로 포장 소성변형 저감을 위한 해석적 연구 (한국도로학회 14(4))", "2012",
     "https://www.kci.go.kr/kciportal/ci/sereArticleSearch/ciSereArtiView.kci?sereArticleSearchBean.artiId=ART001685955",
     "감속·정차·온도·포장 선택을 함께 검토해야 함",
     "모든 정류장 파임의 원인을 이 논문 하나로 단정하지 않는다.", "R2 원문확인"),
    ("F09", "Talebsafa — Optimization of Concrete Pavement Design to Truck Platoon Loading (UTA)", "2021",
     "https://mavmatrix.uta.edu/civilengineering_dissertations/417/",
     "횡방향 위치 분산과 집중 통과 비교 개념",
     "트럭·콘크리트 수치를 한국 트램·아스팔트에 옮기지 않는다.", "R2 원문확인"),
    ("F10", "YouTube Blog — YouTube Shorts deep dive", "2025-01-28",
     "https://blog.youtube/creator-and-artist-stories/youtube-shorts-deep-dive/",
     "첫 순간의 관심 유발, 짧은 이야기의 완결", "알고리즘 공식·유지율 보장으로 쓰지 않는다.", "R2 원문확인"),
    ("F11", "YouTube Blog — Cracking the code to YouTube Shorts", "2026-01-15",
     "https://blog.youtube/creator-and-artist-stories/cracking-the-code-to-youtube-shorts/",
     "친숙한 소재, 예상 뒤집기", "장르 전체 통계로 단정하지 않는다.", "R2 원문확인"),
    ("F12", "서울시 — ‘포트홀 예방’ 버스정류장 8곳 ‘콘크리트 포장’한다", "2020-07",
     "https://mediahub.seoul.go.kr/archives/1288523",
     "정류장 구간 조립식(공장 제작) 콘크리트 포장, 2010년 공항대로 정류장 시범 설치, 2020년 8곳(경인로·공항대로·송파대로) 시공",
     "‘포트홀 0건’, ‘아스팔트 7년·콘크리트 20년’ 같은 시 발표 수치는 화면·내레이션에 넣지 않는다.",
     "검색확인 · 원문 접근 차단 → 녹음 전 게시일·문장 재대조"),
    ("F13", "서울 공항로 버스전용차로 정거장 조립식 콘크리트 포장 초기 공용성 (한국도로학회 학술대회)", "2011 추정",
     "https://koreascience.kr/article/CFKO201123552845418.pdf",
     "버스전용차로 정거장 구간의 아스팔트 포장에서 소성변형 등 손상이 잦아 프리캐스트 슬래브로 교체",
     "슬래브 규격·성능 수치는 화면에 넣지 않는다. 제목·저자·연도 원문 확인 전까지 화면 카드 사용 금지.",
     "검색확인 · 원문 접근 차단 → 서지 재확인"),
    ("F14", "강남구 — 선릉로 버스정류장 고강성 프리캐스트 콘크리트 포장", "2025 전후(재확인)",
     "https://www.gangnam.go.kr/board/B_000031/1074649/view.do?mid=ID01",
     "자치구 단위에서도 정류장 구간을 프리캐스트 콘크리트로 교체한 사례",
     "구청 발표의 성능 설명을 독립 검증 결과로 쓰지 않는다. 내레이션에는 넣지 않고 롱폼 B롤 참고로만.",
     "검색확인 · 원문 접근 차단"),
]

# ---------------------------------------------------------------------------
# 쇼츠 15컷 · 9:16
# kf: 사용하는 키프레임 / mode: Flow 생성 방식
#   T2I = 이미지 생성(키프레임) · F2V = Frames to Video(시작 프레임, 필요 시 끝 프레임)
#   ING = Ingredients to Video(참조 이미지 최대 3장) · TRIM = 이전 클립에서 잘라 씀
# ---------------------------------------------------------------------------
SHORT = [
    dict(id="S01", vo="정류장 앞에만 콘크리트 판을 깐 도로, 보신 적 있으십니까?",
         role="훅 · 생활 관찰",
         visual="노면 높이 로우앵글. 첫 프레임부터 버스 뒷바퀴가 화면을 빠져나가고, 카메라는 남아 줄눈이 반듯한 콘크리트 판과 그 앞 아스팔트의 두 줄 홈을 보여준다.",
         camera="고정 → 마지막 1초 아주 느린 푸시인", sfx="버스 출발음, 공기 브레이크 해제음 1회. 인트로 음악 없음",
         kf="KF01", mode="F2V 시작=KF01", src="F12; F13",
         check="첫 프레임에 이미 홈과 판이 보이는가 / 노면 글자·노선번호 없음"),
    dict(id="S02", vo="멋이 아닙니다. 아스팔트로는 버티기 힘든 자리라서죠.",
         role="긴장",
         visual="수직 부감으로 전환. 붉은 버스차로 안에 색이 다른 직사각형 판 구간이 놓이고, 판 직전 아스팔트에만 바퀴 자국 두 줄이 짙게 보인다.",
         camera="수직 부감 고정, 아주 느린 하강", sfx="도시 환경음, 주행음 멀리",
         kf="KF02", mode="F2V 시작=KF02", src="F12; F13",
         check="부감에서 판 구간과 홈 구간이 한눈에 대비되는가"),
    dict(id="S03", vo="무거운 버스가 매번 같은 자리에 서고, 다시 출발하니까요.",
         role="원리 1 · 정차",
         visual="버스 앞바퀴가 감속해 판 직전 홈 위에 멈춘다. 타이어 옆면과 노면이 한 화면.",
         camera="타이어 높이 측면 고정", sfx="감속 타이어음, 공기 브레이크 쉬익",
         kf="KF03", mode="F2V 시작=KF03", src="F08",
         check="바퀴가 홈 안쪽에 정확히 정지 / 타이어 회전과 이동 속도 일치"),
    dict(id="S04", vo="서울시도 일부 정류장을 이렇게 바꿔 왔습니다.",
         role="실제 대응",
         visual="야간 공사 재현. 크레인이 공장에서 만든 콘크리트 판 한 장을 정류장 차로에 내려놓는다. 작업자는 멀리, 얼굴 없음.",
         camera="중거리 고정, 판이 내려앉는 순간까지", sfx="크레인 모터, 판이 자리 잡는 둔한 소리",
         kf="KF04", mode="F2V 시작=KF04", src="F12",
         check="'재현' 표기(편집) / 실제 공사 현장·기관 로고로 오인되지 않게"),
    dict(id="S05", vo="그런데 정류장이 아니어도, 바퀴가 같은 줄로 모이는 버스가 있습니다.",
         role="전환 · 본론 진입",
         visual="굴절 차량이 유도 전용 차로로 다가온다. 차로 중앙에 둥근 마커가 일정 간격으로 박혀 있다.",
         camera="낮은 정면 3/4, 차량이 화면을 채울 때까지 고정", sfx="낮은 전기 구동음, 타이어 굴림",
         kf="KF05", mode="F2V 시작=KF05", src="F02",
         check="굴절부 1개·3축 유지 / 로고·번호 없음"),
    dict(id="S06", vo="도로 속 자석을 따라 달리는, 국내 개발 바이모달 트램입니다.",
         role="대상 소개",
         visual="차체 하부 시점. 앞축 근처 센서 장치가 노면의 둥근 마커 위를 손 한 뼘 높이로 지나간다. 접촉·빛·레이저 없음.",
         camera="노면 높이에서 차량 진행 방향으로 함께 이동(1회)", sfx="주행음만. 스캔음·비프 없음",
         kf="KF06", mode="F2V 시작=KF06", src="F01; F02",
         check="센서와 마커 비접촉 / 빛나는 선·레이저 없음"),
    dict(id="S07", vo="스스로 길을 잡으니, 매번 거의 같은 줄을 지나가죠.",
         role="원리 2 · 집중",
         visual="높은 수직 부감. 유도 차로의 바퀴 자국은 두 줄의 좁은 띠로 겹치고, 연석 너머 일반 차로의 자국은 더 넓게 퍼져 있다.",
         camera="수직 부감 고정", sfx="통과음 리듬 2회",
         kf="KF07", mode="F2V 시작=KF07", src="F05; F09",
         check="한 장의 연속 사진 / 두 차로가 같은 도로로 읽히는가 / 차량이 좌우로 흔들리지 않음"),
    dict(id="S08", vo="시험실에서는 이걸 바퀴 하나로 재현합니다.",
         role="실험 전환",
         visual="휠트래킹 시험기 전경. 하중판을 얹은 작은 바퀴가 아스팔트 시편 위를 한 줄로 오간다.",
         camera="50mm 정면 고정", sfx="시험기 모터, 규칙적인 굴림음",
         kf="KF08", mode="F2V 시작=KF08", src="F06",
         check="바퀴가 옆으로 움직이지 않음 / 계기판 숫자 없음"),
    dict(id="S09", hold=1.0, vo="바퀴가 지나간 뒤를 보십시오.",
         role="★ 관찰 지시",
         visual="매크로. 바퀴가 시편을 누르고 화면 밖으로 굴러 나간다. 카메라는 바퀴를 따라가지 않는다.",
         camera="저각 사광 매크로 고정", sfx="굴림음 멀어짐, 음악 빠짐",
         kf="KF09A→KF09B", mode="F2V 시작=KF09A 끝=KF09B", src="F07",
         check="바퀴가 나간 뒤 카메라 정지 유지"),
    dict(id="S10", hold=1.2, vo="눌린 자리가, 다 돌아오지 않습니다.",
         role="★ 잔류변형",
         visual="같은 매크로 구도. 사광 그림자 안에 아주 얕은 눌림이 남아 있다. 골재는 단단한 형상 그대로.",
         camera="고정(정지에 가까운 2초)", sfx="정적. 시험실 공조음만",
         kf="KF09B", mode="TRIM(S09 클립 끝 2초) 또는 F2V 시작=끝=KF09B", src="F07",
         check="눌림이 '파임'이 아니라 '얕은 잔류'로 읽히는가 / 골재 녹음·흐름 없음"),
    dict(id="S11", hold=0.8, vo="같은 줄을 수천 번 밟으면, 그 차이가 홈이 됩니다.",
         role="★ 누적 · 보상",
         visual="시간 압축. 바퀴가 오가는 동안 시편 표면에 홈이 깊어진다. 마지막에 쇠자를 가로로 얹으면 자 밑으로 빛이 새어 나온다.",
         camera="45° 사광 고정, 자가 놓이는 순간까지", sfx="굴림음 펄스가 빨라지다 멈춤 → 쇠자 내려놓는 금속음 1회",
         kf="KF10A→KF10B", mode="F2V 시작=KF10A 끝=KF10B", src="F06; F07",
         check="자 밑 빛 틈이 보이는가 / 홈 양옆이 칼로 판 것처럼 날카롭지 않은가 / 숫자·눈금 판독 불가"),
    dict(id="S12", hold=0.6, vo="그럼 개발진은 몰랐을까요?",
         role="반전 질문",
         visual="기록실 테이블. 스탠드 불이 켜진다. 덮인 회색 파일들, 돋보기.",
         camera="정면 고정, 불 켜짐 1회", sfx="스위치 딸깍, 실내 정적",
         kf="KF11", mode="F2V 시작=KF11", src="—",
         check="읽히는 글자 없음"),
    dict(id="S13", vo="이천구년 관련 특허에, 변형 위험과 콘크리트 포장 대책이 이미 나옵니다.",
         role="★ 반전 · 근거",
         visual="KF11 위에 실제 특허 서지 화면 캡처(번호·출원일·출원인)를 편집 합성. 해당 문단만 밑줄로 강조.",
         camera="편집 줌 1회(합성 카드)", sfx="종이 넘김 1회",
         kf="KF11 + 실제 문서 캡처", mode="TRIM(S12 클립) + 편집 합성", src="F01",
         check="생성형 가짜 문서 금지 / 캡처는 KIPRIS·Google Patents 원문"),
    dict(id="S14", vo="남은 질문은 하나. 실제 도로에 적용했느냐입니다.",
         role="판단 기준",
         visual="현장으로 복귀. 장갑 낀 손이 실제 유도 차로의 바퀴 자국 위에 쇠자를 얹는다(시험실 S11과 같은 동작).",
         camera="노면 높이 고정", sfx="쇠자 금속음, 먼 차량음",
         kf="KF19", mode="F2V 시작=KF19", src="분석",
         check="결함 단정 없이 '확인 행위'로 읽히는가"),
    dict(id="S15", vo="레일은 없앨 수 있어도, 길의 설계까지 없앨 수는 없습니다.",
         role="결론 · 수미상관",
         visual="S01과 같은 정류장 로우앵글. 이번엔 굴절 유도 차량이 떠나고, 콘크리트 판과 길이 남는다.",
         camera="고정. 차량 이탈 후 1초 유지", sfx="떠나는 주행음 → 도시 환경음 1초",
         kf="KF12", mode="F2V 시작=KF12", src="종합",
         check="노면이 저절로 복원되는 역재생 금지 / S01과 구도 일치"),
]

# ---------------------------------------------------------------------------
# 롱폼 42주샷 · 16:9
# ---------------------------------------------------------------------------
LONG_SECTIONS = [
    ("L01", "콜드오픈 — 정류장 바닥의 두 줄"),
    ("L02", "정류장 바닥이 콘크리트인 이유"),
    ("L03", "자석은 길을 알려줄 뿐"),
    ("L04", "지나간 뒤에도 남는 눌림"),
    ("L05", "무게가 아니라 자리를 바꾼다"),
    ("L06", "홈은 한 번에 생기지 않는다"),
    ("L07", "개발진은 정말 몰랐을까"),
    ("L08", "실제 운행 기록은 따로 본다"),
    ("L09", "같은 자리를 밟는 차를 위한 길"),
    ("L10", "세금은 어디까지 계산해야 하나"),
    ("L11", "정밀함은 문제이자 도구"),
]

LONG = [
    # L01
    dict(id="C01", sec="L01", vo="출근길 버스정류장 앞, 도로 한 구간만 네모난 콘크리트 판으로 깔린 곳이 있습니다. 판과 판 사이에는 반듯한 줄눈이 나 있죠.",
         visual="정류장 로우앵글. 버스가 떠나며 판과 줄눈이 드러난다.", kf="KF01(16:9)", mode="ING 참조=KF01 · 8초×2", src="F12",
         sfx="버스 출발음, 도시 환경음", check="쇼츠 S01과 같은 장소로 읽히는가"),
    dict(id="C02", sec="L01", vo="그 바로 앞 아스팔트는 어떨까요. 바퀴 자국을 따라 살짝 내려앉고, 옆으로 밀려 낮은 물결처럼 솟은 곳도 보입니다.",
         visual="판 직전 아스팔트를 사광으로 따라가는 슬라이더. 홈과 측방 융기.", kf="KF01-D", mode="F2V 시작=KF01-D · 8초×2", src="F08; F13",
         sfx="환경음 낮춤", check="융기는 낮고 완만하게. 깨짐·포트홀 과장 금지"),
    dict(id="C03", sec="L01", vo="오늘 이야기는 이 두 줄의 홈에서 시작합니다. 그리고 이 질문을, 정류장 밖 도로 전체로 넓혀 보게 만드는 차가 있습니다. 국내에서 개발된 바이모달 트램입니다.",
         visual="두 줄 홈에서 틸트 업 → 멀리 유도 차로 위 굴절 차량 실루엣.", kf="KF01 → KF05", mode="F2V 시작=KF01-D 끝=KF05(16:9) · 8초", src="F02",
         sfx="낮은 지속음 시작", check="두 장소가 같은 도시 룩"),
    dict(id="C04", hold=0.8, sec="L01", vo="이런 차를 두고, 너무 정확하게 달려서 길을 망가뜨렸다는 이야기가 돌기도 합니다. 정말 그럴까요. 끝까지 보시면, 다음에 정류장에 섰을 때 발밑이 다르게 보이실 겁니다.",
         visual="차량 앞바퀴 접지면으로 천천히 다가가 정지.", kf="KF05", mode="ING 참조=KF05 · 8초×2", src="—",
         sfx="음악 낮추고 타이어 굴림 전면", check="결론을 미리 말하지 않는 질문형"),
    # L02
    dict(id="C05", sec="L02", vo="먼저 정류장부터 보겠습니다. 버스는 이곳에서 속도를 줄이고, 멈추고, 다시 출발합니다. 승객을 태우려고 매번 거의 같은 위치에 서죠.",
         visual="버스 감속·정차·출발 3단계를 같은 측면 구도로 연결.", kf="KF03", mode="F2V 시작=KF03 · 8초×2", src="F08",
         sfx="감속음, 공기 브레이크, 출발음", check="정차 위치가 홈과 일치"),
    dict(id="C06", sec="L02", vo="무거운 차가 느리게 움직이거나 서 있으면, 포장이 하중을 받는 시간이 길어집니다. 여름 한낮처럼 포장이 뜨거울 때는 더 불리하고요. 교차로 포장을 연구한 국내 논문도 감속과 정차, 온도를 함께 따져야 한다고 봅니다.",
         visual="한낮 열기 속 정류장, 노면 위 아지랑이(실제 현상 수준). 붉은 열화상 색 금지.", kf="KF01-H", mode="ING 참조=KF01 · 8초×2", src="F08",
         sfx="매미 소리 낮게, 공회전음", check="온도 수치·열화상 없음"),
    dict(id="C07", sec="L02", vo="그래서 서울시는 이천십년, 공항대로의 한 버스정류장에 공장에서 만든 콘크리트 판을 깔아 시험했습니다. 이천이십년에는 정류장 여덟 곳에 같은 방식을 적용하겠다고 발표했죠.",
         visual="야간 공사 재현: 크레인이 판을 내려놓음 → 편집에서 서울시 발표 서지 카드(날짜·제목) 4초.", kf="KF04", mode="F2V 시작=KF04 · 8초×2", src="F12",
         sfx="크레인, 판 안착음", check="'재현' 표기 / 서지 카드는 원문 확인 후"),
    dict(id="C08", sec="L02", vo="핵심은 간단합니다. 무게가 같은 자리에, 같은 방식으로, 반복해서 실리는 곳은 도로를 다르게 설계해야 한다는 겁니다. 이 원리를 기억해 두시고, 바이모달 트램으로 넘어가 보겠습니다.",
         visual="완성된 판 구간 위를 버스가 지나가는 부감.", kf="KF02", mode="F2V 시작=KF02 · 8초×2", src="F12; F13",
         sfx="통과음, 지속음 복귀", check="판 위 바퀴 자국 없음을 과장하지 않음"),
    # L03
    dict(id="C09", sec="L03", vo="겉모습은 마디가 있는 긴 버스입니다. 고무 타이어로 달리고, 차체 가운데에서 꺾입니다. 운전자가 직접 몰 수도 있고, 도로에 묻힌 자석을 따라 스스로 길을 잡을 수도 있도록 설계됐습니다.",
         visual="굴절 차량 3/4 측면 전경 → 굴절부가 곡선에서 꺾이는 모습.", kf="KF05", mode="ING 참조=KF05 · 8초×2", src="F02",
         sfx="주행 앰비언스", check="굴절부 1개·3축 유지"),
    dict(id="C10", sec="L03", vo="여기서 흔한 오해가 하나 있습니다. 자석이 차를 끌어당기는 게 아닙니다. 도로에 일정한 간격으로 묻힌 자석은 이정표에 가깝습니다. 차 밑의 센서가 그 자기장을 읽고, 제어장치가 조향을 맞춥니다.",
         visual="센서가 마커 위를 지나가는 노면 시점 → 마커 하나를 담은 도로 코어 시편(실험대 위).", kf="KF06 → KF06-C", mode="F2V 시작=KF06 · 8초 + F2V 시작=KF06-C · 8초", src="F01; F02",
         sfx="주행음, 시험실 정적", check="비접촉 / 레이저·빛 없음 / 자석 크기 과장 금지"),
    dict(id="C11", sec="L03", vo="그러니까 역할이 둘로 나뉩니다. 자석과 센서는 어디로 갈지를 정하고, 무게는 여전히 타이어와 도로가 받습니다.",
         visual="센서에서 타이어 접지면으로 카메라가 한 번에 이동.", kf="KF06", mode="ING 참조=KF05,KF06 · 8초", src="F01; F02",
         sfx="가벼운 전환 폴리", check="하부 부품 순간이동·소실 없음"),
    dict(id="C12", sec="L03", vo="레일을 없앴다는 말은, 무게를 받칠 시설이 필요 없다는 뜻이 아닙니다. 철도에서 레일과 침목이 하던 일을, 이제 도로가 해야 한다는 뜻에 가깝습니다.",
         visual="타이어 접지면에서 노면 절개 단면으로 내려가 포장층·지지층을 본다(공사 현장 실사 절개).", kf="KF15", mode="F2V 시작=KF15 · 8초×2", src="F06",
         sfx="낮은 지속음", check="층 두께 숫자 없음"),
    # L04
    dict(id="C13", sec="L04", vo="도로 안을 들여다보겠습니다. 포장을 잘라 보면, 크고 작은 돌 알갱이가 빽빽하게 박혀 있습니다. 이 골재를 아스팔트 바인더가 붙잡고, 둘이 함께 무게를 견딥니다.",
         visual="절단 시편 단면 매크로 슬라이더.", kf="KF13", mode="F2V 시작=KF13 · 8초×2", src="F07",
         sfx="돌 질감 폴리", check="골재가 젤리처럼 보이지 않음"),
    dict(id="C14", sec="L04", vo="흔히 아스팔트가 엿처럼 녹아 흐른다고 말하지만, 정확한 그림은 아닙니다. 그렇다고 아무리 눌러도 꿈쩍 않는 돌덩이도 아닙니다.",
         visual="같은 단면, 사광 각도만 천천히 변함.", kf="KF13", mode="F2V 시작=KF13 · 8초", src="F07",
         sfx="정적에 가까움", check="녹는 표현 금지"),
    dict(id="C15", sec="L04", vo="포장 시험실에서는 이걸 바퀴 하나로 확인합니다. 하중을 실은 바퀴를 포장 시편 위에서 같은 줄을 따라 오가게 하는 시험입니다. 바퀴가 누르면, 포장이 아주 조금 내려갑니다.",
         visual="휠트래킹 시험기 전경 → 바퀴 접지부 근접.", kf="KF08", mode="F2V 시작=KF08 · 8초×2", src="F06",
         sfx="시험기 모터, 굴림 리듬", check="바퀴 측방 이동 없음 / 계기 숫자 없음"),
    dict(id="C16", hold=1.5, sec="L04", vo="중요한 건 바퀴가 떠난 다음입니다. 대부분은 되돌아오지만, 아주 일부가 남습니다. 다음 바퀴는 이미 조금 달라진 포장을 다시 누르게 되죠. 이 작은 차이가 쌓이는 것, 그게 오늘의 핵심입니다.",
         visual="쇼츠 S09–S10과 같은 매크로. 바퀴 이탈 후 얕은 잔류 눌림을 2초 이상 유지.", kf="KF09A→KF09B", mode="F2V 시작=KF09A 끝=KF09B · 8초 + 정지 유지", src="F07",
         sfx="굴림음 후 0.8초 정적", check="잔류가 식별되는가 / 과장 금지"),
    # L05
    dict(id="C17", sec="L05", vo="이제 조건을 하나만 바꿔 보겠습니다. 차의 무게, 타이어, 속도, 지나가는 횟수, 도로 재료는 모두 그대로 둡니다. 바꾸는 건 바퀴가 지나가는 좌우 위치뿐입니다.",
         visual="같은 시험기 두 대가 나란히(같은 방, 같은 구도). 하나는 바퀴 위치가 매 왕복 조금씩 옮겨지고, 하나는 고정.", kf="KF08-W", mode="F2V 시작=KF08-W · 8초×2", src="F05; F09",
         sfx="두 시험기 같은 음량", check="두 장비가 동일 형상 / 분할화면 아님"),
    dict(id="C18", sec="L05", vo="사람이 모는 버스는 같은 차로를 달려도, 바퀴 위치가 매번 조금씩 다릅니다. 운전자마다, 날마다 차이가 나죠. 이 좌우 분산을 휠 원더링이라고 부릅니다.",
         visual="일반 차로 부감. 여러 버스가 각기 조금 다른 좌우 위치로 통과(차체 가림으로 시간 생략).", kf="KF14", mode="F2V 시작=KF14 · 8초×2", src="F05; F09",
         sfx="통과별 분리된 펄스", check="한 대가 지그재그로 달리지 않음"),
    dict(id="C19", sec="L05", vo="자동 유도 차량은 다릅니다. 같은 경로를 따르도록 만든 차이니, 바퀴 자국이 훨씬 좁은 띠 안에 겹치기 쉽습니다.",
         visual="유도 차로·일반 차로 나란한 부감(쇼츠 S07 동일 자산).", kf="KF07", mode="F2V 시작=KF07 · 8초×2", src="F05",
         sfx="같은 리듬 반복", check="두 차로 대비가 한 장면에서 읽힘"),
    dict(id="C20", sec="L05", vo="전체 통과 횟수는 같아도, 특정한 한 줄이 눌리는 횟수는 늘어납니다. 한 번 누르는 힘이 세진 게 아니라, 같은 곳을 더 자주 누르는 겁니다. 정류장 앞에서 보던 조건 하나가, 달리는 구간으로 옮겨 오는 셈이죠.",
         visual="KF07 → KF07B 시간 경과: 유도 차로의 두 띠만 조금 더 짙고 얕게 내려앉음.", kf="KF07→KF07B", mode="F2V 시작=KF07 끝=KF07B · 8초", src="F05; F09",
         sfx="리듬만 반복, 음량 고정", check="힘이 세지는 연출(진동·충격파) 금지"),
    # L06
    dict(id="C21", sec="L06", vo="그렇게 쌓인 영구 변형이 바퀴 자국을 따라 길게 이어지면, 우리가 아는 그 홈이 됩니다. 소성변형, 흔히 러팅이라고 부르는 현상입니다.",
         visual="시험기 시편 홈 시간 압축(쇼츠 S11 자산, 쇠자 전까지).", kf="KF10A→KF10B", mode="F2V 시작=KF10A 끝=KF10B · 8초", src="F06; F07",
         sfx="굴림 펄스", check="횟수·기간 숫자 없음"),
    dict(id="C22", sec="L06", vo="칼로 깎아낸 것처럼 생기는 게 아닙니다. 포장 속이 더 촘촘하게 다져지고, 일부는 옆으로 밀리고, 그 아래 층의 변형까지 보태집니다. 시험실에서는 쇠자를 홈 위에 걸쳐 그 깊이를 잽니다.",
         visual="홈 단면 시편 매크로(다짐·측방 밀림) → 쇠자와 빛 틈.", kf="KF13-R → KF10B", mode="F2V 시작=KF13-R · 8초 + TRIM(S11 끝)", src="F06; F07",
         sfx="쇠자 금속음 1회", check="측방 융기 과장 금지"),
    dict(id="C23", sec="L06", vo="그래서 결과는 조건에 따라 달라집니다. 온도와 재료, 두께, 시공 품질, 그리고 차가 얼마나 느리게 지나가느냐.",
         visual="한낮 정류장 / 공사 현장 다짐 롤러 / 느린 버스를 같은 정면 구도로 순차.", kf="KF01-H, KF15, KF03", mode="TRIM(C06·C12·C05 여분) · 신규 없음", src="F06; F08",
         sfx="장면별 짧은 환경음", check="새 키프레임 만들지 않음(자산 재사용)"),
    dict(id="C24", sec="L06", vo="결국 질문은 자동이냐 사람이냐가 아닙니다. 그 하중과 그 반복을, 도로가 견디도록 준비했느냐입니다.",
         visual="일반 버스와 유도 차량이 같은 포장 위를 각각 지나감(같은 구도 매치컷).", kf="KF03, KF05", mode="ING 참조=KF03,KF05 · 8초×2", src="F06; F08",
         sfx="두 차량 같은 음향 무게", check="사람=안전 / 자동=파괴 이분법 금지"),
    # L07
    dict(id="C25", hold=0.8, sec="L07", vo="여기까지 오면 이런 의문이 듭니다. 차를 만든 사람들은, 도로가 이렇게 될 수 있다는 걸 몰랐을까요?",
         visual="기록실. 스탠드 불이 켜짐.", kf="KF11", mode="F2V 시작=KF11 · 8초", src="—",
         sfx="스위치, 0.5초 정적", check="읽히는 글자 없음"),
    dict(id="C26", sec="L07", vo="이천구년에 출원된 특허 하나가 있습니다. 한국철도기술연구원과 현대엔지니어링이 출원한, 바이모달 트램의 유도용 자석을 도로에 설치하는 방법에 관한 문서입니다.",
         visual="실제 특허 서지 캡처 합성(번호·출원일·출원인) 4–6초 → 마커 코어 시편으로 복귀.", kf="KF11 + 캡처, KF06-C", mode="TRIM + 편집 합성", src="F01",
         sfx="종이 넘김 1회", check="생성형 문서 금지 / 출원인 표기 원문 대조"),
    dict(id="C27", sec="L07", vo="이 문서에는, 일반 아스팔트 포장에 하중이 집중되면 소성변형과 전단변형이 생길 수 있다고 적혀 있습니다. 대책으로 콘크리트 포장과 변형을 줄이는 재료, 정기적인 보수도 언급합니다.",
         visual="해당 문단 캡처 하이라이트 → 아스팔트 시편과 콘크리트 시편에 같은 마커가 박힌 비교 정물.", kf="KF16", mode="F2V 시작=KF16 · 8초", src="F01",
         sfx="두 재질 접촉음", check="'사후 개보수 공사' 재현으로 보이지 않게"),
    dict(id="C28", sec="L07", vo="그러니 아무도 예상하지 못했다는 이야기는 사실과 다릅니다. 다만 문서에 대책이 있다는 것과, 실제 현장에 그 대책이 적용됐다는 것은 다른 문제입니다. 그건 설계도와 시공 기록으로 따로 확인해야 합니다.",
         visual="현장 쇠자 측정(쇼츠 S14 자산).", kf="KF19", mode="F2V 시작=KF19 · 8초×2", src="F01",
         sfx="쇠자 금속음, 먼 차량음", check="결함 단정 없음"),
    # L08
    dict(id="C29", sec="L08", vo="실제 운행 기록도 나눠서 보겠습니다. 인천교통공사는 이천십팔년, 청라 지역에 바이모달 트램 네 대를 투입한다고 발표했습니다. 만들자마자 버려진 차라는 이야기와는 결이 다릅니다.",
         visual="실제 공사 발표 서지 카드 → 차량기지에 서 있는 굴절 차량(재현).", kf="KF17", mode="F2V 시작=KF17 · 8초×2", src="F03",
         sfx="차량기지 환경음", check="당시 실제 도색 재현 시도 금지(일반화 외형)"),
    dict(id="C30", sec="L08", vo="이천이십년 공사의 해명자료에는 차체 균열, 배터리 장치의 고압 퓨즈 불량, 기어박스 누유가 나옵니다. 공사는 균열 보강과 퓨즈 개선을 설명했고, 누유는 개선 중이라고 밝혔습니다.",
         visual="해명자료 서지 카드 → 정비 피트에서 차체 하부를 비추는 작업등(부품 결함 형상 재현 없음).", kf="KF17-P", mode="F2V 시작=KF17-P · 8초×2", src="F04",
         sfx="정비 공간 환경음, 경고음 없음", check="균열·누유 형상 임의 재현 금지"),
    dict(id="C31", sec="L08", vo="이건 운영기관의 당시 설명입니다. 문제가 모두 해결됐다는 독립적인 판정과는 구분해야 합니다.",
         visual="작업등이 꺼지고 차량 측면 실루엣.", kf="KF17-P", mode="TRIM(C30 여분)", src="F04",
         sfx="정적", check="—"),
    dict(id="C32", sec="L08", vo="그리고 이 자료 어디에도, 도로가 파여서 이런 고장이 났다는 연결은 없습니다. 고장 기록은 무엇이 고장 났는지를 알려줄 뿐, 왜 고장 났는지는 별도의 조사가 필요합니다.",
         visual="차량과 도로를 한 화면에 두고 카메라 정지. 연결선·화살표 없음.", kf="KF17", mode="TRIM(C29 여분)", src="F03; F04",
         sfx="대사 끝 0.6초 쉼", check="연쇄 고장 연출 금지"),
    # L09
    dict(id="C33", sec="L09", vo="그렇다면 같은 자리를 반복해서 밟는 차에는 어떤 길이 필요할까요. 처음에 본 정류장 바닥이 힌트입니다.",
         visual="정류장 판 구간으로 복귀(KF01).", kf="KF01", mode="TRIM(C01 여분)", src="F12",
         sfx="도시 환경음", check="수미상관 1차"),
    dict(id="C34", sec="L09", vo="먼저 실제 축하중과 운행 횟수, 온도와 속도를 놓고 포장을 정합니다. 아스팔트라면 변형에 강한 혼합물과 시공 품질을 따지고, 필요한 구간은 콘크리트 포장을 검토합니다.",
         visual="아스팔트 시편·콘크리트 시편 비교 정물(KF16) 슬라이더.", kf="KF16", mode="ING 참조=KF16 · 8초×2", src="F01; F06",
         sfx="재질 차이 폴리", check="'콘크리트가 무조건 정답' 구도 금지"),
    dict(id="C35", sec="L09", vo="겉만 단단하게 바꿔서는 부족합니다. 그 아래 지지층과 배수, 자석을 묻은 방식, 나중에 보수하는 방법까지 함께 설계해야 합니다.",
         visual="도로 절개면: 표층 → 지지층 → 배수관 → 마커 매립 위치를 한 번의 틸트로.", kf="KF15", mode="F2V 시작=KF15 · 8초×2", src="F01; F06",
         sfx="낮은 층별 폴리", check="층 두께·철근량 숫자 없음"),
    dict(id="C36", sec="L09", vo="새 차를 도로 위에 올리는 일이 아니라, 그 차가 매일 지나갈 길까지 하나의 시스템으로 만드는 일입니다.",
         visual="유도 차로 전경 풀아웃: 차량·정류장·차로가 한 화면.", kf="KF05", mode="ING 참조=KF05,KF02 · 8초", src="종합",
         sfx="지속음 상승 없이 유지", check="—"),
    # L10
    dict(id="C37", sec="L10", vo="비용 이야기도 빼놓을 수 없습니다. 도로까지 새로 손봐야 한다면, 차라리 철도가 낫지 않느냐는 질문이죠. 답은, 같은 조건으로 비교했느냐에 달려 있습니다.",
         visual="실험대 위 축소 노선 모형(차량·정거장·차량기지). 숫자·그래프 없음.", kf="KF18", mode="F2V 시작=KF18 · 8초×2", src="분석",
         sfx="중립 실내음", check="가상의 비교 모형임을 내레이션·표기로 유지"),
    dict(id="C38", sec="L10", vo="같은 구간에서, 같은 승객을, 같은 기간 동안 나른다고 놓고 차량값과 도로, 정거장, 포장 보수, 부품 수급, 운행이 멈췄을 때의 대체 수송까지 함께 계산해야 합니다.",
         visual="모형 위를 카메라가 차량 → 도로 → 정거장 → 정비고 순으로 한 방향 이동.", kf="KF18", mode="ING 참조=KF18 · 8초×2", src="분석",
         sfx="목소리 전면, 타격음 없음", check="금액·영수증·막대그래프 생성 금지"),
    dict(id="C39", sec="L10", vo="연구개발비와 차량값, 건설비를 한 숫자로 섞으면 무엇이 비쌌는지 알 수 없습니다. 무엇에 얼마를 썼고, 무엇을 검증했고, 보수는 누가 책임지는가. 세금을 제대로 감시하는 질문은 여기서 시작됩니다.",
         visual="모형 전체를 한 프레임에 두고 정지. 비교 범위 전체가 보인다.", kf="KF18", mode="ING 참조=KF18 · 8초×2", src="분석",
         sfx="목소리 전면", check="낭비·우위 판정 아님"),
    dict(id="C40", sec="L11", vo="이 문제는 지난 이야기가 아닙니다. 미국 연방도로청은 자동화 차량이 도로에 미치는 영향을 다룬 보고서에서, 바퀴의 좌우 분산이 줄면 포장 홈이 커질 수 있다고 봤습니다.",
         visual="FHWA 보고서 서지 카드 4초 → 고속도로 차로 부감, 차량들이 차로 안에서 조금씩 다른 위치로 통과.", kf="KF20", mode="F2V 시작=KF20 · 8초×2", src="F05",
         sfx="고속 주행음", check="특정 한국 차량 시험 결과로 오인 금지"),
    dict(id="C41", sec="L11", vo="반대로 주행 위치를 조금씩 나눠 주는 제어가 포장에 유리할 수 있다는 연구도 소개합니다. 같은 정밀함이 하중을 모으는 데도, 나누는 데도 쓰일 수 있다는 겁니다.",
         visual="쇼츠 S07 부감(KF07)으로 돌아와, 유도 차로의 좁은 띠를 다시 본다.", kf="KF07", mode="TRIM(C19 여분)", src="F05",
         sfx="같은 통과 리듬", check="급격한 차선 내 사행 연출 금지"),
    dict(id="C42", sec="L11", vo="다음에 정류장 앞에서 그 네모난 판을 보시면, 한 번 떠올려 보십시오. 레일은 없앨 수 있어도, 길의 설계까지 없앨 수는 없습니다.",
         visual="쇼츠 S15와 같은 엔딩: 정류장 로우앵글에서 유도 차량이 떠나고 길이 남는다.", kf="KF12", mode="ING 참조=KF12 · 8초", src="종합",
         sfx="첫 장면의 주행음 → 환경음 1초", check="역재생 복원 금지"),
]

# ---------------------------------------------------------------------------
# 키프레임 카탈로그 (Flow 이미지 생성 → 영상 시작/끝 프레임 또는 Ingredients)
# order: 생성 순서(위험한 것부터). pair: 쌍 컷이면 선행 KF — 반드시 선행 확정 후 참조 첨부해 순차 생성
# ---------------------------------------------------------------------------
KEYFRAMES = [
    dict(id="KF09A", order=1, used="S09 · C16", locks="[LAB LOCK — WHEEL TRACKER] [STYLE LOCK — LAB]", pair="",
         prompt="THE SUBJECT IS ONE SMALL PATCH OF ASPHALT SLAB SURFACE directly under a test wheel, seen in extreme close-up at the height of the slab with low grazing side light. Nearest to camera the flat specimen surface shows individual angular stones. The test wheel rests on the patch, pressing it, its tread filling about a third of the frame width; beyond the wheel the same flat surface continues and falls out of focus. The empty flat surface on the near side of the wheel is as important to this frame as the wheel itself. Vertical 9:16 framing."),
    dict(id="KF09B", order=2, used="S09–S10 · C16", locks="[LAB LOCK — WHEEL TRACKER] [STYLE LOCK — LAB]", pair="KF09A",
         prompt="Reproduce the attached reference frame exactly: same camera position, height, lens, distance, light, grade and background. Change one thing only: the wheel has rolled out of frame, and where it pressed, the surface now holds a very shallow, soft-edged depression, barely deeper than the stones around it, made visible only by a thin crescent of shadow from the grazing light. The stones keep their hard angular shapes; nothing is cracked, melted or torn."),
    dict(id="KF10A", order=3, used="S11 · C21", locks="[LAB LOCK — WHEEL TRACKER] [STYLE LOCK — LAB]", pair="",
         prompt="THE SUBJECT IS THE STRAIGHT WHEEL PATH ACROSS A RECTANGULAR ASPHALT SLAB SPECIMEN, seen from a 45-degree angle with low raking light along its length. The slab is clamped in a steel mould inside the test chamber; the test wheel is parked at the far end of the slab. A plain steel straightedge without markings lies across the slab at right angles to the wheel path, resting flat on the surface, with no light visible beneath it. Vertical 9:16 framing."),
    dict(id="KF10B", order=4, used="S11 · C21–C22", locks="[LAB LOCK — WHEEL TRACKER] [STYLE LOCK — LAB]", pair="KF10A",
         prompt="Reproduce the attached reference frame exactly: same camera, light, grade, mould, wheel position and straightedge position. Change one thing only: along the wheel path the slab now carries one smooth, shallow, rounded groove about the width of the wheel, with a faint low rounded rise along each edge. Under the straightedge a thin sliver of light shows through where the groove dips. The groove edges are soft and rounded, not knife-cut; the stones stay hard and angular."),
    dict(id="KF01", order=5, used="S01 · C01 · C33", locks="[CITY BUS LOCK] [STOP SITE LOCK] [STYLE LOCK — FIELD]", pair="",
         prompt="THE SUBJECT IS THE ROAD SURFACE OF A BUS STOPPING ZONE, seen from just above road level looking along the bus lane. Nearest to camera lies the worn asphalt with two shallow wheel-path grooves catching the low sunlight; a little further along begins the first precast concrete slab with a straight thin joint across the lane, and more slabs continue beyond it. Further along the lane the rear of a city bus is pulling away from the island shelter. The road surface is as important to this frame as the bus; keep it wide open and sharp. Vertical 9:16 framing."),
    dict(id="KF01-D", order=13, used="C02 · C03", locks="[STOP SITE LOCK] [STYLE LOCK — FIELD]", pair="KF01",
         prompt="Using the attached reference for place, light and grade: the camera now sits closer to the road, travelling sideways across the worn asphalt just before the first concrete slab. The two shallow wheel-path grooves and a faint low ripple of shoved asphalt beside them fill the frame. No potholes, no cracks wider than a hairline, no water. Horizontal 16:9 framing."),
    dict(id="KF01-H", order=17, used="C06 · C23", locks="[CITY BUS LOCK] [STOP SITE LOCK] [STYLE LOCK — FIELD]", pair="KF01",
         prompt="Using the attached reference for place and composition: midsummer noon, hard high sun, faint natural heat shimmer just above the asphalt, a city bus idling at the shelter with its front wheel resting in the groove before the first slab. No thermal colours, no glow. Horizontal 16:9 framing."),
    dict(id="KF02", order=6, used="S02 · C08", locks="[STOP SITE LOCK] [STYLE LOCK — FIELD]", pair="KF01",
         prompt="THE SUBJECT IS THE BUS LANE SEEN STRAIGHT DOWN FROM HIGH ABOVE, running from the bottom edge of the frame to the top edge. Nearest the start of the lane the reddish-brown asphalt carries two darker wheel-path bands; then the lane changes to a run of pale precast concrete slabs with straight joints beside the island shelter roof; after the slabs the asphalt resumes. General traffic lanes on both sides are empty. Vertical 9:16 framing."),
    dict(id="KF03", order=7, used="S03 · C05 · C23 · C24", locks="[CITY BUS LOCK] [STOP SITE LOCK] [STYLE LOCK — FIELD]", pair="KF01",
         prompt="THE SUBJECT IS THE CONTACT BETWEEN ONE FRONT TYRE OF A CITY BUS AND THE ROAD, seen from the side at tyre height. The tyre is rolling slowly into the shallow groove just before the first concrete slab; the slab joint is visible a short distance ahead of the tyre. The tyre sidewall, the contact patch and the groove are all sharp. Vertical 9:16 framing."),
    dict(id="KF04", order=11, used="S04 · C07", locks="[STOP SITE LOCK] [STYLE LOCK — FIELD]", pair="",
         prompt="THE SUBJECT IS ONE PRECAST CONCRETE SLAB BEING SET DOWN INTO AN EMPTY RECTANGULAR BED IN THE BUS LANE at night, hanging level from four chains under a small mobile crane, a hand's width above its bed. Work lights give a soft white glow; two workers in plain high-visibility vests stand far away with their backs to camera. Neighbouring slabs already laid continue beyond. No logos, no text on vests, crane or barriers. Vertical 9:16 framing."),
    dict(id="KF05", order=8, used="S05 · C04 · C09 · C36", locks="[VEHICLE LOCK — GUIDED ARTICULATED] [GUIDEWAY SITE LOCK] [STYLE LOCK — FIELD]", pair="",
         prompt="THE SUBJECT IS A GUIDED ARTICULATED VEHICLE APPROACHING ALONG ITS OWN LANE, seen from a low front three-quarter angle. Nearest to camera the empty lane with its single centre line of small flush round plugs runs toward the vehicle; the vehicle is further along the lane, its whole length visible including the one bellows joint and all three axles. The empty lane in front of the vehicle is as important to this frame as the vehicle itself. Vertical 9:16 framing."),
    dict(id="KF06", order=9, used="S06 · C10 · C11", locks="[VEHICLE LOCK — GUIDED ARTICULATED] [GUIDEWAY SITE LOCK] [STYLE LOCK — FIELD]", pair="KF05",
         prompt="THE SUBJECT IS THE GAP BETWEEN A FLAT SENSOR UNIT UNDER THE FRONT OF THE VEHICLE AND ONE ROUND FLUSH PLUG IN THE ROAD, seen from road level beside the front tyre. The sensor unit is a plain dark rectangular box mounted crosswise under the floor a hand's width above the road; the round plug sits flush in the lane centre directly below it. Nothing touches; no light, no beam, no glow passes between them. The front tyre stands to one side of the plug. Vertical 9:16 framing."),
    dict(id="KF06-C", order=19, used="C10 · C26", locks="[SPECIMEN LOCK — CUT SLAB] [STYLE LOCK — LAB]", pair="",
         prompt="THE SUBJECT IS A CYLINDRICAL CORE SAMPLE OF ROAD PAVEMENT STANDING ON A MATTE BLACK BENCH, sliced in half lengthwise so its cut face looks at the camera. In the top layer of the core a small plain cylindrical magnet sits in a drilled pocket sealed flush with the road surface. Around the core is wide empty black space. Horizontal 16:9 framing."),
    dict(id="KF07", order=10, used="S07 · C19 · C20 · C41", locks="[GUIDEWAY SITE LOCK — ADJACENT LANE VARIANT] [STYLE LOCK — FIELD]", pair="",
         prompt="THE SUBJECT IS THE PATTERN OF TYRE MARKS ON TWO NEIGHBOURING LANES, seen straight down from high above, both lanes running from the bottom edge of the frame to the top edge. On the guided lane the tyre marks form two narrow, sharply defined darker bands on either side of the line of round plugs. Across the low kerb, on the ordinary lane, the tyre marks are spread into two much wider, softer, fainter bands. No vehicles in frame. Vertical 9:16 framing."),
    dict(id="KF07B", order=20, used="C20", locks="[GUIDEWAY SITE LOCK — ADJACENT LANE VARIANT] [STYLE LOCK — FIELD]", pair="KF07",
         prompt="Reproduce the attached reference frame exactly: same camera, height, light, grade and lanes. Change one thing only: on the guided lane the two narrow bands are now slightly darker and very slightly sunken, catching a thin line of shadow; the ordinary lane is unchanged. Horizontal 16:9 framing."),
    dict(id="KF08", order=12, used="S08 · C15", locks="[LAB LOCK — WHEEL TRACKER] [STYLE LOCK — LAB]", pair="KF10A",
         prompt="Using the attached reference for machine design, light and grade: THE SUBJECT IS THE WHOLE WHEEL-TRACKING MACHINE seen from the front at bench height, the glass chamber doors open, the test wheel mid-stroke on the slab. Wide dark space on both sides of the machine. Vertical 9:16 framing."),
    dict(id="KF08-W", order=21, used="C17", locks="[LAB LOCK — WHEEL TRACKER] [STYLE LOCK — LAB]", pair="KF08",
         prompt="Using the attached reference for machine design, light and grade: two identical wheel-tracking machines stand side by side in the same room, both at the same distance from camera and both fully visible. Identical slabs, identical wheels, identical weight stacks. One single continuous photograph, no split, no seam. Horizontal 16:9 framing."),
    dict(id="KF11", order=14, used="S12–S13 · C25–C26", locks="[ARCHIVE LOCK] [STYLE LOCK — LAB]", pair="",
         prompt="THE SUBJECT IS AN EMPTY PATCH OF DARK WOODEN TABLETOP under a desk lamp, kept clear for a document to be placed later. Around that clear patch: plain closed grey folders, a magnifying glass, reading glasses. The clear tabletop patch is as important to this frame as the objects. Vertical 9:16 framing."),
    dict(id="KF12", order=16, used="S15 · C42", locks="[VEHICLE LOCK — GUIDED ARTICULATED] [STOP SITE LOCK] [STYLE LOCK — FIELD]", pair="KF01",
         prompt="Reproduce the attached reference frame exactly: same camera position, height, lens, light, grade, shelter, slabs and grooves. Change one thing only: the vehicle pulling away further along the lane is now the guided articulated vehicle instead of the city bus. Vertical 9:16 framing."),
    dict(id="KF13", order=18, used="C13 · C14", locks="[SPECIMEN LOCK — CUT SLAB] [STYLE LOCK — LAB]", pair="",
         prompt="THE SUBJECT IS THE SAW-CUT FACE OF AN ASPHALT SLAB seen straight on in macro, filling the frame from edge to edge, the stones sharp and angular, the black binder a thin film between them, low side light raking across the cut face. Horizontal 16:9 framing."),
    dict(id="KF13-R", order=22, used="C22", locks="[SPECIMEN LOCK — CUT SLAB] [STYLE LOCK — LAB]", pair="KF13",
         prompt="Reproduce the attached reference frame exactly in camera, light and grade. Change one thing only: the slab surface along the top of the cut face now dips in one smooth shallow rounded groove; under the groove the stones sit slightly closer together, and beside the groove the surface rises very slightly. The stones keep their shapes. Horizontal 16:9 framing."),
    dict(id="KF14", order=23, used="C18", locks="[CITY BUS LOCK] [STOP SITE LOCK] [STYLE LOCK — FIELD]", pair="KF02",
         prompt="Using the attached reference for place, height and grade: the bus lane seen straight down between stops, on plain reddish-brown asphalt. One city bus is passing, slightly left of the lane centre. The worn tyre bands on the asphalt are wide and soft-edged. Horizontal 16:9 framing."),
    dict(id="KF15", order=24, used="C12 · C35 · C23", locks="[STYLE LOCK — FIELD]", pair="",
         prompt="THE SUBJECT IS THE CLEAN VERTICAL WALL OF A NARROW ROAD-WORKS TRENCH cut across a city lane, seen straight on in daylight: the dark asphalt surface layer at the top, a thicker grey crushed-stone base below it, compacted earth further down, and a plain drainage pipe end visible near the bottom. No people, no machines, no signs. Horizontal 16:9 framing."),
    dict(id="KF16", order=25, used="C27 · C34", locks="[SPECIMEN LOCK — CUT SLAB] [STYLE LOCK — LAB]", pair="KF06-C",
         prompt="THE SUBJECT IS TWO ROAD SAMPLE BLOCKS STANDING SIDE BY SIDE on a matte black bench at the same distance from camera: on the left a dark asphalt block, on the right a pale concrete block, each with the same small round flush plug set into its top surface. Equal light, equal size, wide empty space around them. Horizontal 16:9 framing."),
    dict(id="KF17", order=26, used="C29 · C32", locks="[VEHICLE LOCK — GUIDED ARTICULATED] [STYLE LOCK — FIELD]", pair="KF05",
         prompt="Using the attached reference for vehicle shape: THE SUBJECT IS THE VEHICLE STANDING ALONE INSIDE A CLEAN, DIM MAINTENANCE DEPOT, seen side-on at waist height, full length visible, concrete floor, high roof lights off, soft daylight from a far doorway. Horizontal 16:9 framing."),
    dict(id="KF17-P", order=27, used="C30 · C31", locks="[VEHICLE LOCK — GUIDED ARTICULATED] [STYLE LOCK — FIELD]", pair="KF17",
         prompt="Using the attached reference for depot, vehicle and grade: seen from inside the inspection pit under the vehicle, one plain work lamp lighting the underside of the floor and the drive area. Nothing broken, nothing leaking, no warning lights, no people. Horizontal 16:9 framing."),
    dict(id="KF18", order=28, used="C37–C39", locks="[STYLE LOCK — LAB]", pair="",
         prompt="THE SUBJECT IS A TABLETOP SCALE MODEL OF ONE CITY TRANSIT CORRIDOR on a matte grey bench: a single model road with one small white articulated vehicle, two small station shelters, and a small depot building at one end, all in plain white and grey model materials. No numbers, no labels, no charts. Wide empty bench space around it. Horizontal 16:9 framing."),
    dict(id="KF19", order=15, used="S14 · C28", locks="[GUIDEWAY SITE LOCK] [STYLE LOCK — FIELD]", pair="KF10B",
         prompt="Using the attached lab reference only for the straightedge: THE SUBJECT IS A PLAIN STEEL STRAIGHTEDGE BEING LAID ACROSS ONE WHEEL PATH OF THE GUIDED LANE by a gloved hand, seen from road level. The line of round plugs is visible beside the wheel path. Only the glove and forearm of the person appear. Vertical 9:16 framing."),
    dict(id="KF20", order=29, used="C40", locks="[STYLE LOCK — FIELD]", pair="",
         prompt="THE SUBJECT IS ONE LANE OF A MULTI-LANE HIGHWAY SEEN STRAIGHT DOWN FROM HIGH ABOVE, with a few plain unbranded cars and trucks spaced far apart, each sitting at a slightly different position across the width of the lane. Plain white lane lines only. No text, no signs. Horizontal 16:9 framing."),
]

# 쇼츠 영상 프롬프트(Frames to Video). 키프레임 프롬프트와 별개로 '움직임'만 기술한다.
SHORT_MOTION = {
    "S01": "0.0-0.6 the bus rear is already moving away; 0.6-3.0 the bus shrinks into the distance; the camera stays still on the road surface; 3.0-4.0 an extremely slow push-in toward the first slab joint. The road does not change.",
    "S02": "Locked overhead view; the camera descends very slightly; one distant car crosses in a general lane. The lane surface does not change.",
    "S03": "The front tyre rolls slowly into frame, decelerates and stops inside the groove just before the slab joint; the tyre rotation matches its speed exactly; the bus body settles slightly on its suspension.",
    "S04": "The hanging slab descends slowly the last hand's width and settles into its bed; the chains slacken; the camera stays locked.",
    "S05": "The vehicle advances steadily toward camera along the lane until its front fills most of the frame; the bellows joint flexes only slightly; the camera stays locked.",
    "S06": "The camera travels forward at road level together with the vehicle; the sensor unit passes over one round plug and then the next; nothing touches, nothing glows.",
    "S07": "Locked overhead view; one guided vehicle passes along its lane with its tyres exactly on the narrow bands; moments later one bus passes in the ordinary lane slightly off-centre.",
    "S08": "The test wheel rolls back and forth along its one straight line, steady rhythm; the camera stays locked; the wheel never moves sideways.",
    "S09": "Start on the first frame with the wheel pressing; the wheel rolls away out of frame; the camera does not follow; the slab surface settles into the end frame.",
    "S11": "Time-lapse: the test wheel passes back and forth many times, faster and faster, as the groove deepens smoothly; the wheel parks; a gloved hand lays the straightedge across and a thin sliver of light appears beneath it, matching the end frame.",
    "S12": "The desk lamp switches on once; dust motes drift; nothing else moves.",
    "S14": "A gloved hand lowers the straightedge across the wheel path and holds it still; a car passes far away.",
    "S15": "The guided vehicle pulls away and shrinks into the distance; after it has gone the camera holds still on the road for one more second. The road surface does not change.",
}
